### ISSUE TITLE
✍️Interpolation is not working with dashes.

### ISSUE THREAD

**Issue by X4V1** [Terran-Source/interpolate-json#6] opened 2021-03-24 16:00 UTC
**Describe the bug**
The interpolation is not working when using dashes.

**To Reproduce**
`interpolation.expand('http://${my-domain}/whatever/', {'my-domain': 'example.com'})`
The output is still "http://${my-domain}/whatever/"

**Expected behavior**
I would expect to have "${my-domain}" replaced by "example.com".

**Environment (please complete the following information):**
 - OS: MacOS 11.1
 - Node.js version 14
 - Version 2.1.3

**Comment by turn-a-round** [comment] 2021-04-14 08:16
This is by design. Hyphen ('-') for json Key is a bad practice & cause all sorts of problem in Javascript world. I'd suggest to go for **_camelCasing_** naming strategy for json keys.

It'd looks like:
`interpolation.expand('http://${myDomain}/whatever/', {myDomain: 'example.com'})`

**Comment by turn-a-round** [comment] 2021-05-12 02:22
Closing the issue.

**Closed** 2021-05-12 02:22 UTC
